# Generated by Django 2.2.2 on 2020-07-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursetag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='courese',
            new_name='course',
        ),
    ]
