# Generated by Django 2.2.2 on 2020-07-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresource',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='名称'),
        ),
    ]
