# Generated by Django 2.2.2 on 2020-04-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='worker_year',
            new_name='worker_years',
        ),
    ]
