# Generated by Django 2.2.2 on 2020-04-29 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200429_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='worker_years',
            new_name='workr_years',
        ),
    ]
