# Generated by Django 2.2.2 on 2020-04-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20200429_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='workr_years',
            new_name='work_years',
        ),
    ]
